import type { Creator, Video } from "../state/types";

export const MockData_AllVideos: Record<string, Video> = {
    "MeNYH8pTT0I": {
      title: "Final Fantasy 4 and Disability",
      thumbnail: "https://i.ytimg.com/vi/MeNYH8pTT0I/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBzaFkI_ZFj6XKaZWw9g-8GI8FX0w",
      videoId_yt: "MeNYH8pTT0I",
      creatorId_yt: "QuestingRefuge",
    },
    "APoEQ1cc0lU": {
      title: "The fake shot that saved WALL-E",
      thumbnail: "https://i.ytimg.com/vi/APoEQ1cc0lU/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBk869MyDDRVzFXRHTh-y-ArhMDsg",
      videoId_yt: "APoEQ1cc0lU",
      creatorId_yt: "Kikikrazed",
    },
    "tCi5k1XCj-E": {
      title: "This is the best scene in Notting Hill",
      thumbnail: "https://i.ytimg.com/vi/tCi5k1XCj-E/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDsettOJhr9Wtegwaom6iCKkkPPsg",
      videoId_yt: "tCi5k1XCj-E",
      creatorId_yt: "Kikikrazed",
    }
  }

export const MockData_AllCreators: Record<string, Creator> = {
  "Kikikrazed" : {
    creatorId_yt: "@kikikrazed",
    name: "Kikikrazed",
    avatarURL: "https://yt3.googleusercontent.com/sasx1iTZchZlzobI02xl-nOqO6jiEhdnTH6yA9bi0jm7-2WQYYvqlP4PFxNh7yi_ToYXARXM=s160-c-k-c0x00ffffff-no-rj",
    videoIds: ["APoEQ1cc0lU", "tCi5k1XCj-E"],
  },
  "QuestingRefuge" : {
    creatorId_yt: "UClmuot4amsrbqglBOJLBwTw",
    name: "Questing Refuge",
    avatarURL: "https://yt3.googleusercontent.com/ytc/AIdro_nMxL8r9S3s3xPv8EDlgQnaqgYy9-WLSRVhYDe8hpi4xMY=s160-c-k-c0x00ffffff-no-rj",
    videoIds: ["MeNYH8pTT0I"],
  },
};

// TODO: Delete this?
export const MockData_CreatorIds: [string, string][] = [
  ["Kikikrazed", "Kikikrazed"],
  ["QuestingRefuge", "QuestingRefuge"],
  ["Voidzilla", "@Voidzilla"],
  ["Bigbluebackpack", "@BigBlueBackpack"],
  ["Legendary Lore", "@TheLegendaryLore"],
  ["Kurzgesagt", "@kurzgesagt"],
  ["CGP Grey", "@CGPGrey"],
  ["Lindsay Ellis", "@lindsayellisvids"],
  ["Jet Lag", "@jetlagthegame"],
  ["Nicole Rafiee", "@NicoleRafiee"],
  ["Psychology With Dr Ana", "@AnaPsychology"],
  ["Folding Ideas", "@FoldingIdeas"],
  ["Nebula", "@nebula"],
  ["Bailey Sarian", "@BaileySarian"],
  ["Juby Philosophy", "@jubyphilosophy"],
  ["Skyehoppers", "@Skyehoppers"],
  ["Innuendo Studios", "@InnuendoStudios"],
  ["Jacob Geller", "@JacobGeller"],
  ["ladyknightthebrave", "@LadyKnightTheBrave"],
  ["Lola Sebastian", "@LolaSebastian"],
  ["Razbuten", "@Razbuten"],
  ["RealEngineering", "@RealEngineering"],
  ["Wendover", "@WendoverProductions"],
  ["Minute Physics", "@minutephysics"],
  ["Tier Zoo", "@TierZoo"],
  ["Legal Eagle", "@LegalEagle"],
  ["Half As Interesting", "@halfasinteresting"],
  ["Adam Neely", "@adamneely"],
  ["Philosophy Tube", "@PhilosophyTube"],
  ["Hbomberguy", "@hbomberguy"],
  ["KaptainKristian", "@kaptainkristian"],
  ["Spectacles", "@spectacles-dm"],
  ["Step Back", "@StepBackHistory"],
  ["Not Just Bikes", "@NotJustBikes"],
  ["Real Life Lore", "@RealLifeLore"],
  ["Carlos Maza (obvs)", "@CarlosMaza"],
  ["Josh Johnson", "@JoshJohnsonComedy"],
  ["More Perfect Union", "@MorePerfectUnion"],
  ["Thought Slime", "@ThoughtSlime"],
  ["Adam Ragusea", "@aragusea"],
  ["Quinn Curio", "@QuinnCurio"],
  ["Sin Squad", "@sinsquad"],
  ["Vlogbrothers", "@vlogbrothers"],
  ["Idea Channel", "@IdeaChannel"],
  ["Jack Saint", "@LackingSaint"],
  ["John Oliver", "@LastWeekTonight"],
  ["Some More News", "@SMN"],
  ["bittnia", "@bittnia"],
  ["Wendigoon", "@Wendigoon"],
  ["Dan McClellan", "@maklelan"],
  ["That Dang Dad", "@ThatDangDad"],
  ["The Leftist Cooks", "@TheLeftistCooks"],
  ["Squid Tips", "@SquidTips"],
  ["Second Thought", "@SecondThought"],
  ["The Financial Diet", "@thefinancialdiet"],
  ["Parkrose Permaculture", "@ParkrosePermaculture"],
  ["PillarOfGarbage", "@PillarofGarbage"],
  ["videogamedunkey", "@videogamedunkey"],
  ["Shaun", "@Shaun_vids"],
  ["Noah Samsen", "@NoahSamsen"],
  ["Funky Frogbait", "@FunkyFrogBait"],
  ["Crimes New Roman", "@CrimesNewRoman"],
  ["Taylor Lorenz", "@TaylorLorenz"],
  ["D'Angelo Wallace", "@DAngeloWallace"],
  ["Siobhan Brier Aguilar", "@SiobhanBrierAguilar"],
  ["Drew Gooden", "@DrewGooden1"],
  ["Jay Foreman", "@JayForeman"],
  ["Kikikrazed", "@KikiKrazed"],
  ["HizzyHay", "@HizzyHay"],
  ["James Delisio", "@JamesDelisio"],
  ["Ze Frank", "@zefrank"],
  ["Max Teeth", "@MaxTeeth"],
  ["James Woodall", "@JamesWoodall"],
  ["Josh with Parentheses", "@JoshwithParentheses"],
  ["PixelADay", "@PixelADay"],
  ["Jarvis Johnson", "@JarvisJohnson"],
  ["Joseph Anderson", "@JosephAndersonChannel"],
  ["Noah Caldwell-Gervais", "@NoahCaldwellGervais"],
  ["Matt Bernstein", "@MattBernstein"],
  ["Izzzyzzz", "@Izzzyzzz"],
  ["StrangeAeons", "@StrangeAeons"],
  ["Eddie Burback", "@EddieBurback"],
  ["Cosmonaut Variety Hour", "@CosmonautVarietyHour"],
  ["MovieBob", "@MovieBobCentral"],
  ["Nerdwriter1", "@Nerdwriter1"],
  ["Afterwords", "@afterwords_"],
  ["Polygon", "@Polygon"],
  ["Let's Game It Out", "@LetsGameItOut"],
  ["The Majority Report", "@TheMajorityReport"],
  ["Action Button", "@ActionButton"],
  ["Alexander Avila", "@alexanderavila"],
  ["Be Kind Rewind", "@BeKindRewind"],
  ["CJ The X", "@CJTheX"],
  ["Codex Entry", "@CodexEntry"],
  ["eliquorice", "@eliquorice"],
  ["TaskMaster", "@Taskmaster"],
  ["Errant Signal", "@ErrantSignal"],
  ["i am a dot.", "@iamadot"],
  ["i am error", "@iamerror"],
  ["LambHoot", "@LambHoot"],
  ["lines in motion", "@LinesInMotion"],
  ["Overly Sarcastic Productions", "@OverlySarcasticProductions"],
  ["Meatcanyon", "@MeatCanyon"],
  ["Egoraptor", "@Egoraptor"],
  ["Sorry About The Mess", "@SorryAboutTheMess"],
  ["Transparency Boo", "@transparencyboo"],
  ["Yhara zayd", "@yharazayd"],
  ["AI In Context", "@AI_In_Context"],
  ["Patrick Boyle", "@PBoyle"],
  ["CoffeeZilla", "@coffeezilla"],
  ["Sloan Stowe", "@sloanstowe"],
  ["Rebecca Watson", "@rebeccawatson"],
  ["JelloApocalypse", "@jelloapocalypse"],
  ["ExplanationPoint", "@explanationpointanime"],
  ["chromalore", "@chromalore"],
  ["Gigguk", "@gigguk"],
  ["Mother's Basement", "@mothersbasement"],
  ["RagnarRox", "@RagnarRoxShow"],
  ["The Gemsbok", "@TheGemsbok"],
  ["Contrapoints", "@ContraPoints"],
  ["Oki's Weird Stories", "@OkisWeirdStories"],
  ["The Soy Pill", "@TheSoyPill"],
  ["Mainley Mandy", "@MainleyMandy"],
  ["Shawn Grenier | The Canvas", "@ShawnGrenier"],
  ["Second Wind", "@SecondWindGroup"],
  ["/noclip", "@noclip"],
  ["Ju Almighty", "@JuAlmighty"],
  ["Robert Reich", "@RBReich"],
  ["Heather Cox Richardson", "@HeatherCoxRichardson"],
  ["Genetically Modified Skeptic", "@GeneticallyModifiedSkeptic"],
  ["Olurinatti", "@olurinatti"],
  ["Zoe Bee", "@zoe_bee"],
  ["Respect The Dead", "@RespectTheDead"],
  ["Hoots", "@hootshootman"],
  ["Jenny Nicholson", "@JennyNicholson"],
  ["Afterthoughts", "@Afterthoughts"],
  ["Verigan", "@Veriganic"],
  ["Theramin Trees", "@TheraminTrees"],
  ["A Healthy Dose of Fran", "@AHealthyDoseofFran"],
  ["Phil Edwards", "@PhilEdwardsInc"],
  ["Noel Miller", "@NoelMiller"],
  ["West Side Tyler", "@WestSideTyler"],
  ["Olivia Unplugged", "@Olivia.Unplugged"],
  ["Patrick Moore", "@PatrickMooreYT"],
  ["Sincerely On Main", "@SincerelyOnMain"],
  ["chriswaves", "@chriswaves"],
  ["Pancake", "@PancakeVideoEssays"],
  ["Sideways", "@Sideways440"],
  ["Reject Convenience", "@RejectConvenience"],
  ["Owl Criticism", "@owlcriticism"],
  ["Ember Green", "@EmberGreen"],
  ["Pure Kino", "@PureKino"],
  ["Nobbel87", "@Nobbel87"],
  ["Quality Culture", "@QualityCulture"],
  ["Allie Meowy", "@AllieMeowy"],
  ["Timbah.On.Toast", "@TimbahOnToast"],
  ["Ryan Beard Productions", "@RyanBeardProductions"],
  ["Adam Something", "@AdamSomething"],
  ["The Elephant Graveyard", "@TheElephantGraveyard"],
  ["Ro Ramdin", "@RoRamdin"],
  ["Hellvetica", "@Hellvetica"],
  ["Andrewism", "@Andrewism"],
  ["Captain Astronaut", "@CaptainAstronaut"],
  ["Kirby Ferguson", "@KirbyFerguson"],
  ["cari can read", "@caricanread"],
  ["Nick DiRamio", "@NickDiRamio"],
  ["Fionapollo", "@Fionapollo"],
  ["History Buffs", "@HistoryBuffsLondon"],
  ["HassledVania", "@HassledVania"],
  ["Well There's Your Problem", "@wtyppod"],
  ["Defunctland", "@Defunctland"],
  ["Mike Rugnetta", "@MikeRugnetta"],
  ["julia cudney", "@juliacudney"],
  ["jax exci", "@JaxExci"],
  ["indietrix", "@Indietrix"],
  ["Radical Soda", "@RadicalSoda"],
  ["Arlo", "@ArloStuff"],
  ["James Jani", "@JamesJani"],
  ["Barry Kramer", "@BarryKramer"],
  ["Johnny 2 Cellos", "@Johnny2Cellos"],
  ["Lord Ravenscraft", "@LordRavenscraft"],
  ["geothebio", "@geothebio"],
  ["For Harriet", "@ForHarriet"],
  ["Friendly Space Ninja", "@FriendlySpaceNinja"],
  ["ThatGuyGlen", "@ThatGuyGlen"],
  ["Treesicle", "@Treesicle"],
  ["SuperEyepatchWolf", "@SuperEyepatchWolf"],
  ["Ana Isabel", "@AnaIsabel"],
  ["CopsHateMoe", "@CopsHateMoe"],
  ["Khadija Mbowe", "@KhadijaMbowe"],
  ["Unlearning Economics", "@UnlearningEconomics"],
  ["Atrocity Guide", "@AtrocityGuide"],
  ["Shonalika", "@Shonalika"],
  ["Tee Noir", "@TeeNoir"],
  ["LaRon Readus", "@LaRonReadus"],
  ["StrucciMovies", "@StrucciMovies"],
  ["Premodernist,", "@Premodernist"],
  ["Townsends,", "@townsends"],
  ["Clint's Reptiles,", "@ClintsReptiles"],
  ["Hank Green,", "@hankgreen"],
  ["Stefan Milo,", "@StefanMilo"],
  ["3blue1brown", "@3blue1brown"],
  ["Steve Mould", "@stevemould"], 
]
